Repository pulp/pulp-cli, pull requests merged in 2024-08, with the labels that each got.

#1036 Automatically add backport labels for release branch
  .ci/scripts/create_release_branch.sh
  .github/workflows/pr_checks.yml
  .github/workflows/release_branch.yml
  cookiecutter/ci/{{ cookiecutter.__project_name }}/.ci/scripts/create_release_branch.sh
  cookiecutter/ci/{{ cookiecutter.__project_name }}/.github/workflows/pr_checks.yml
  cookiecutter/ci/{{ cookiecutter.__project_name }}/.github/workflows/release_branch.yml
  cookiecutter/ci/{{ cookiecutter.__project_name }}/lint_requirements.txt
Labels: no-issue, no-changelog

#1038 Fix error in safe_calls_only without fake_mode
  CHANGES/pulp-glue/1037.bugfix
  pulp-glue/pulp_glue/common/context.py
  pulp-glue/pulp_glue/core/context.py
Labels: backport-0.27

#1031 Allow list retrieve all entries and add iterator
  CHANGES/pulp-glue/+list_infinite.feature
  CHANGES/pulp-glue/+list_iterator.feature
  pulp-glue/pulp_glue/common/context.py
  pulp-glue/pyproject.toml
  pulp-glue/tests/test_entity_list.py
  pyproject.toml
Labels: no-issue

#1040 Add support of contains/startswith to RPM content
  CHANGES/687.feature
  pulp-glue/pulp_glue/rpm/context.py
  pulpcore/cli/rpm/content.py
  tests/scripts/pulp_rpm/test_content.sh
Labels: no-issue

#1013 Add OAuth2 ClientCredentials flow support
  CHANGES/926.feature
  docs/user/reference/_SUMMARY.md
  docs/user/reference/authentication.md
  pulp-glue/pulp_glue/common/authentication.py
  pulp-glue/pulp_glue/common/openapi.py
  pulpcore/cli/common/generic.py
Labels: no-issue

#1042 Fix release-branch due to changes in docs/ layout/location.
  .ci/scripts/create_release_branch.sh
  cookiecutter/ci/{{ cookiecutter.__project_name }}/.ci/scripts/create_release_branch.sh
  pulp-glue/pyproject.toml
  pyproject.toml
Labels: no-issue, no-changelog

#1043 Further fixes to the release-workflow due to docs changes.
  cookiecutter/ci/{{ cookiecutter.__project_name }}/pyproject.toml.update
  pyproject.toml
Labels: no-issue, no-changelog

#1046 Fix failure-edge-cases in outh2-client-workflow.
  CHANGES/pulp-glue/+fix_auth_regression.bugfix
  pulp-glue/pulp_glue/common/openapi.py
Labels: no-issue, backport-0.28

#1051 Refactor the auth mechanism selection algorithm
  CHANGES/pulp-glue/+fix_auth_selection_regressions.bugfix
  pulp-glue/pulp_glue/common/openapi.py
  pulp-glue/tests/test_auth_provider.py
  pulpcore/cli/common/generic.py
Labels: no-issue, backport-0.28
