Repository pulp/pulp-cli, pull requests merged in 2024-09, with the labels that each got.

#1050 Add a new guard clause to the oauth2 client credentials flow.
  CHANGES/pulp-glue/1050.bugfix
  pulp-glue/pulp_glue/common/authentication.py
  pulp-glue/tests/test_authentication.py
Labels: no-issue

#1058 Update cookiecutter templates
  .github/workflows/test.yml
  cookiecutter/ci/cookiecutter.json
  cookiecutter/ci/{{ cookiecutter.__project_name }}/.ci/gen_certs.py
  cookiecutter/ci/{{ cookiecutter.__project_name }}/.ci/nginx.conf.j2
  cookiecutter/ci/{{ cookiecutter.__project_name }}/.ci/run_container.sh
  cookiecutter/ci/{{ cookiecutter.__project_name }}/.ci/settings/settings.py
  cookiecutter/ci/{{ cookiecutter.__project_name }}/lint_requirements.txt
  pyproject.toml
Labels: no-issue, no-changelog

#1062 Fix stray click import in pulp-glue
  pulp-glue/pulp_glue/common/context.py
  pulp-glue/pulp_glue/rpm/context.py
Labels: no-issue, no-changelog

#1069 Fixed the logic of the warning in list
  CHANGES/pulp-glue/1068.bugfix
  pulp-glue/pulp_glue/common/context.py
Labels: backport-0.28

#1076 Declare compatibility with python 3.13
  .github/workflows/test.yml
  CHANGES/+python3.13.misc
  CHANGES/pulp-glue/+python3.13.misc
  pulp-glue/pyproject.toml
  pyproject.toml
Labels: no-issue

#1077 Declare compatibility with python 3.13
  .github/workflows/test.yml
  CHANGES/+python3.13.misc
  CHANGES/pulp-glue/+python3.13.misc
  pulp-glue/pyproject.toml
  pyproject.toml
Labels: no-issue

#1081 Add --file-url support
  CHANGES/file_url.feature
  pulpcore/cli/file/content.py
  pulpcore/cli/python/content.py
  pulpcore/cli/rpm/content.py
  tests/scripts/pulp_file/test_content.sh
  tests/scripts/pulp_python/test_content.sh
  tests/scripts/pulp_rpm/test_content.sh
Labels: no-issue

#1087 Fix from_config messing up headers
  CHANGES/+from_config.bugfix
  pulp-glue/pulp_glue/common/context.py
  pulp-glue/tests/conftest.py
Labels: no-issue, backport-0.29
