Repository pulp/pulp-cli, pull requests merged in 2024-06, with the labels that each got.

#974 Only set auth_provider if no cert was provided
  CHANGES/+cli_cert_auth.bugfix
  pulp-glue/pulp_glue/common/openapi.py
  pulpcore/cli/common/generic.py
Labels: no-issue, backport-0.25

#981 Bump the requests version
  pulp-glue/pyproject.toml
Labels: no-issue, no-changelog, backport-0.25

#980 Introduce ViewSetContext
  CHANGES/+viewset_context.devel
  CHANGES/pulp-glue/+viewset_context.devel
  pulp-glue/pulp_glue/common/context.py
  pulp-glue/pulp_glue/core/context.py
  pulpcore/cli/common/generic.py
  pulpcore/cli/core/orphan.py
Labels: no-issue

#986 Revert "Bump the requests version"
  CHANGES/985.bugfix
  pulp-glue/pyproject.toml
Labels: backport-0.25

#989 Fix python tests to be domain compatible
  tests/scripts/pulp_python/test_distribution.sh
Labels: no-issue, no-changelog

#991 Fix python tests to be domain compatible
  tests/scripts/pulp_python/test_distribution.sh
Labels: no-issue, no-changelog

#995 Improve validation logic
  pulp-glue/pulp_glue/common/openapi.py
Labels: no-issue, no-changelog

#997 Don't test docs on release branches
  .github/workflows/docs.yml
  .github/workflows/kanban.yml
  cookiecutter/docs/{{ cookiecutter.__project_name }}/.github/workflows/docs.yml
  cookiecutter/docs/{{ cookiecutter.__project_name }}/doc_requirements.txt
  cookiecutter/docs/{{ cookiecutter.__project_name }}/docs/en/index.html
  cookiecutter/docs/{{ cookiecutter.__project_name }}/staging_docs/admin/guides/.gitkeep
  cookiecutter/docs/{{ cookiecutter.__project_name }}/staging_docs/admin/learn/.gitkeep
  cookiecutter/docs/{{ cookiecutter.__project_name }}/staging_docs/admin/reference/.gitkeep
  cookiecutter/docs/{{ cookiecutter.__project_name }}/staging_docs/admin/tutorials/.gitkeep
  cookiecutter/docs/{{ cookiecutter.__project_name }}/staging_docs/dev/guides/.gitkeep
  cookiecutter/docs/{{ cookiecutter.__project_name }}/staging_docs/dev/learn/.gitkeep
  cookiecutter/docs/{{ cookiecutter.__project_name }}/staging_docs/dev/reference/.gitkeep
  cookiecutter/docs/{{ cookiecutter.__project_name }}/staging_docs/dev/tutorials/.gitkeep
  cookiecutter/docs/{{ cookiecutter.__project_name }}/staging_docs/user/guides/.gitkeep
  cookiecutter/docs/{{ cookiecutter.__project_name }}/staging_docs/user/learn/.gitkeep
  cookiecutter/docs/{{ cookiecutter.__project_name }}/staging_docs/user/reference/.gitkeep
  cookiecutter/docs/{{ cookiecutter.__project_name }}/staging_docs/user/tutorials/.gitkeep
Labels: no-issue, no-changelog

#999 Update CI
  .ci/container_setup.d/README
  .ci/run_container.sh
  .ci/settings/settings.py
  .github/workflows/docs.yml
  .github/workflows/test.yml
  .gitignore
  lint_requirements.txt
Labels: no-issue, no-changelog
