Repository pulp/pulp-cli, pull requests merged in 2025-01, with the labels that each got.

#1118 Update base_url in test if content_origin is null
  tests/scripts/pulp_file/test_distribution.sh
Labels: no-issue, no-changelog

#1120 Fix the host/port for the (relative) base_url test
  tests/scripts/pulp_file/test_distribution.sh
Labels: no-issue, no-changelog, backport-0.30

#1123 Remove aspects of tests not testing the cli
  tests/scripts/pulp_file/test_distribution.sh
  tests/scripts/pulp_rpm/test_rpm_sync_publish.sh
Labels: no-issue, no-changelog, backport-0.30

#1127 Pinned packaging according to its Calver nature
  CHANGES/1125.misc
  CHANGES/pulp-glue/1125.misc
  pulp-glue/pyproject.toml
  pyproject.toml
Labels: no-issue
