Repository pulp/pulp-cli, pull requests merged in 2025-05, with the labels that each got.

#1182 Add support for new replicate features
  CHANGES/+replicate-policy.feature
  CHANGES/+replicate-q-select.feature
  pulpcore/cli/core/upstream_pulp.py
  tests/scripts/pulpcore/test_upstream_pulp.sh
Labels: no-issue

#1186 Remove support and tests for 2to3 migration
  CHANGES/+2to3-migrate.removal
  pulpcore/cli/migration/__init__.py
  pulpcore/cli/migration/context.py
  pulpcore/cli/migration/locale/de/LC_MESSAGES/messages.mo
  pulpcore/cli/migration/locale/de/LC_MESSAGES/messages.po
  pulpcore/cli/migration/locale/messages.pot
  pulpcore/cli/migration/plan.py
  pulpcore/cli/migration/pulp2.py
  pulpcore/cli/migration/py.typed
  pyproject.toml
  tests/scripts/pulp_2to3_migration/plan.json
  tests/scripts/pulp_2to3_migration/test_plan.sh
  tests/scripts/pulp_2to3_migration/test_pulp2.sh
Labels: no-issue

#1187 Remove support for deprecated RPM features with newer versions
  CHANGES/+remove-old-rpm-features.removal
  CHANGES/pulp-glue/+remove-old-rpm-features.removal
  pulp-glue/pulp_glue/rpm/context.py
  pulpcore/cli/rpm/repository.py
  tests/scripts/pulp_rpm/gpgcheck_test.sh
  tests/scripts/pulp_rpm/test_rpm_sync_publish.sh
Labels: no-issue

#1189 Pin click to z-streams
  pyproject.toml
Labels: no-issue, no-changelog, backport-0.27, backport-0.28, backport-0.29, backport-0.30, backport-0.31, backport-0.32

#1191 Pin click to z-streams
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  CHANGES/+click.dependency.bugfix
  lint_requirements.txt
  pulp-glue/pyproject.toml
  pyproject.toml
Labels: no-issue, backport-0.31

#1192 Pin click to z-streams
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  CHANGES/+click.dependency.bugfix
  lint_requirements.txt
  pulp-glue/pyproject.toml
  pyproject.toml
Labels: no-issue

#1193 Pin click to z-streams
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  CHANGES/+click.dependency.bugfix
  lint_requirements.txt
  pulp-glue/pyproject.toml
  pyproject.toml
Labels: no-issue

#1194 Pin click to z-streams
  .ci/nginx.conf.j2
  .ci/run_container.sh
  .ci/scripts/check_click_for_mypy.py
  .ci/settings/settings.py
  .github/dependabot.yml
  .github/workflows/cookiecutter.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/release_branch.yml
  .github/workflows/test.yml
  CHANGES/+click.dependency.bugfix
  Makefile
  pulp-glue/pyproject.toml
  pyproject.toml
  test_requirements.txt
Labels: no-issue

#1190 Bump click [pulp-536]
  .ci/scripts/check_click_for_mypy.py
  CHANGES/+click_8.2.feature
  cookiecutter/ci/{{ cookiecutter.__project_name }}/.ci/scripts/check_click_for_mypy.py
  pulpcore/cli/core/task_group.py
  pulpcore/cli/rpm/prune.py
  pyproject.toml
  tests/test_help_pages.py
Labels: no-issue
